name: workflow_02_event_triggers

on:
  # we use object notation in case we need to specify other parameters
  workflow_dispatch:
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest 
    steps:
      - name: show the event name
        run: echo ${{ github.event_name }}
